on:
  workflow_call:
    inputs:
      IMAGE:
        required: true
        type: string
    secrets:
      GDBPLUGINS_DOCKERHUB_USER:
        required: true
      GDBPLUGINS_DOCKERHUB_TOKEN:
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.GDBPLUGINS_DOCKERHUB_USER }}
          password: ${{ secrets.GDBPLUGINS_DOCKERHUB_TOKEN }}
      -
        uses: docker/setup-buildx-action@v2
        id: builder
      -
        name: Builder name
        run: echo ${{ steps.builder.outputs.name }}
      -
        name: Build against ${{ inputs.IMAGE  }}
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.builder.outputs.name }}
          context: .
          build-args: |
            IMAGE=${{ inputs.IMAGE }}
          tags: gdbplugin-${{ inputs.IMAGE }}
